# Change these first
owner: KendallDoesCoding
repo: monitoring

sites:
  - name: Portfolio
    url: https://www.kendalldoescoding.tech
  - name: A Very Mogul Christmas!
    url: https://kendalldoescoding.tech/mogulchristmas
  - name: Let It Be - 1970 Album by The Beatles
    url: https://kendalldoescoding.tech/letitbe
  - name: Typing Game 2
    url: https://kendalldoescoding.tech/typinggame2
  - name: Tic Tac Toe
    url: https://kendalldoescoding.tech/tictactoe

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: kendalldoescoding.tech
  # baseUrl: /monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
